learning_templates/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

app_name = 'basicapp'

urlpatterns = [
    url('other', views.other, name = 'other'),
    url('relative', views.relative, name = 'relative'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views


urlpatterns = [
    path('', views.index, name = 'index'),
    path('admin', admin.site.urls),
    path('basicapp', include('basicapp.urls')),
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'name':"sam curran", 'Number':10}
    return render(request, 'basicapp/index.html', context_dict)

def other(request):
    return render(request, 'basicapp/other.html')

def relative(request):
    return render(request, 'basicapp/relative_url_template.html')

learning_templates/templates/basicapp/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class = "navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="jumbotron">
        <ul class="nav navbar-nav">
          <li><a class = "navbar-brand" href="{% url 'index' %}">Brand</a></li>
          <li><a class = "navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class = "navbar-link" href="{% url 'basicapp:other' %}">Other</a></li>
        </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/basic.html"%}
{% block body_block %}
  <h1>This is the Index Page</h1>
  <h1>{{name|cut:'curran'}}</h1>
  <h1>{{Number|add:"100"}}</h1>
{% endblock %}

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/basic.html"%}
{% block body_block %}
<h1>This is the other page</h1>
{% endblock %}

learning_templates/templates/basicapp/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
      <h1>This is the Relative URL Page</h1>
      <a href="{% url 'basicapp:other' %}">The Other Page</a>
      <a href="{% url 'admin:index' %}">The Admin Page</a>
      <a href="{% url 'index' %}">The Index Page</a>
    </div>
    </div>
  </body>
</html>